(* This file was generated by Eliom-distillery. Feel free to use it, modify it,
   and redistribute it as you wish. *)

let%server application_name = "h42n42"
let%client application_name = Eliom_client.get_application_name ()

let%server () =
  Ocsipersist_settings.set_db_file "local/var/data/h42n42/h42n42_db"

(* Create a module for the application. See
   https://ocsigen.org/eliom/manual/clientserver-applications for more
   information. *)
module%shared App = Eliom_registration.App (struct
    let application_name = application_name
    let global_data_path = Some ["__global_data__"]
  end)

(* As the headers (stylesheets, etc) won't change, we ask Eliom not to update
   the <head> of the page when changing page. (This also avoids blinking when
   changing page in iOS). *)
let%client _ = Eliom_client.persist_document_head ()

(* Define a service for the [] or '/' or root path with a GET method *)
let%server main_service =
  Eliom_service.create ~path:(Eliom_service.Path [])
    ~meth:(Eliom_service.Get Eliom_parameter.unit) ()

(* Insert into the client client context the server defined value *)
let%client main_service = ~%main_service

[%%shared open Eliom_content]
[%%client open Js_of_ocaml]
[%%client open Js_of_ocaml_lwt]
[%%client open Js_of_ocaml.Dom_html]
[%%client open Html.D]
[%%client open Lwt.Syntax]


(* --------------- *)
(* GLOBAL STATE    *)
(* --------------- *)

[%%client
type global_state = {
  mutable mouse_x: int;
  mutable mouse_y: int;
  mutable creet_count: int;
}

let global = {
  mouse_x = 0;
  mouse_y = 0;
  creet_count = 0;
}

(* Initialize global mouse tracking *)
let () =
  let _ = Dom_html.addEventListener 
    window 
    (Dom_html.Event.mousemove)
    (Dom_html.handler (fun evt -> 
      global.mouse_x <- evt##.clientX;
      global.mouse_y <- evt##.clientY;
      Js._true))
    Js._false
  in
  ()
]


(* --------------- *)
(* World COMPONENT *)
(* --------------- *)

(* World component *)
let%client world_component () =
  Html.D.div
    ~a:[Html.D.a_class ["world"]]
    [ Html.D.div ~a:[Html.D.a_class ["river"]] []
    ; Html.D.div ~a:[Html.D.a_class ["grass"]] []
    ; Html.D.div ~a:[Html.D.a_class ["hospital"]] []
    ]


(* ------------- *)
(* HUB COMPONENT *)
(* ------------- *)

(* Get stats function *)
let%client get_stats () =
  let width = window##.innerWidth in
  let height = window##.innerHeight in
  let total_parts = 6 in (* 1 + 4 + 1 *)
  let part_height = float_of_int height /. float_of_int total_parts in
  (width, height, part_height)

let%client get_section (part_height, y_height) = 
  let river_end = part_height in
  let grass_end = part_height +. (4.0 *. part_height) in
  let section = 
    if y_height < river_end then "River"
    else if y_height < grass_end then "Grass"
    else "Hospital"
  in
  section

(* HUD component *)
let%client hud_component () =
  let stats_container = div ~a:[a_class ["hud-stats"]] [] in

  let update_stats () =
    let (width, height, part_height) = get_stats () in
    let current_section = get_section (part_height, float_of_int global.mouse_y) in
    Eliom_content.Html.Manip.replaceChildren stats_container
      [ div [txt (Printf.sprintf "Resolution: %dx%d" width height)]
      ; div [txt (Printf.sprintf "Mouse: (%d, %d)" global.mouse_x global.mouse_y)]
      ; div [txt (Printf.sprintf "Inside: %s" current_section)]
      ; div [txt (Printf.sprintf "Creets: %d" global.creet_count)]
      ]
  in

  (* Initial update *)
  update_stats ();

  (* Add resize event listener *)
  let _ = Dom_html.addEventListener 
    window 
    (Dom_html.Event.resize)
    (Dom_html.handler (fun _ -> update_stats (); Js._true))
    Js._false
  in

  (* Add mousemove event listener for HUD updates *)
  let _ = Dom_html.addEventListener 
    window 
    (Dom_html.Event.mousemove)
    (Dom_html.handler (fun _ -> 
      update_stats (); 
      Js._true))
    Js._false
  in

  div
    ~a:[a_class ["hud"]]
    [ div
        ~a:[a_class ["hud-content"]]
        [ div [txt "simulation running"]
        ; stats_container
        ]
    ]


(* --------------- *)
(* Utils           *)
(* --------------- *)

let%client get_current_time () =
  let date = new%js Js.date_now in
  (Js.to_float date##getTime) /. 1000.0
  [@@warning "-unused-value-declaration"]


(* --------------- *)
(* CREET COMPONENT *)
(* --------------- *)

[%%client
type health_status = 
  | Healthy
  | Sick of { lifetime: float }
  | Berserk of { lifetime: float }
  | Mean of { lifetime: float }
[@@warning "-unused-constructor"]

type creet_state = {
  mutable x: float;
  mutable y: float;
  mutable vx: float;
  mutable vy: float;
  id: int;
  mutable health: health_status;
  mutable grabbed: bool;
  element: Html_types.div Html.elt;
}
[@@warning "-unused-field"]
]

(* Global counter for unique IDs *)
let%client next_creet_id = ref 0

(* Generate a unique ID *)
let%client generate_unique_id () =
  let id = !next_creet_id in
  next_creet_id := !next_creet_id + 1;
  id

(* Create a single creet *)
let%client create_creet id start_x start_y =
  let (health, extra_class) =
    if id = 3 then
      (Berserk { lifetime = 10.0 }, "berserk")
    else if id = 7 then
      (Mean { lifetime = 10.0 }, "mean")
    else if id = 1 then
      (Sick { lifetime = 10.0 }, "sick")
    else
      (Healthy, "")
  in

  (* Add extra class depending on state *)
  let creet_div =
    div
      ~a:[ a_class ["creet"; extra_class]; a_id (Printf.sprintf "creet-%d" id) ] [ txt "🐛" ]
  in

  (* Initialize creet *)
  {
    x = start_x;
    y = start_y;
    vx = Random.float 2.0 -. 1.0;
    vy = Random.float 2.0 -. 1.0;
    id;
    grabbed = false;
    health;
    element = creet_div;
  }

(* Update creet position *) 
let%client update_creet_position creet =
  let size = match creet.health with
    | Mean _ -> 34.0
    | Berserk { lifetime } -> 40.0 *. lifetime
    | _ -> 40.0
  in

  let (width, height, _) = get_stats () in
  let width_f = float_of_int width in
  let height_f = float_of_int height in

  (* Update position based on grabbed state *)
  if creet.grabbed then (
    (* Follow mouse cursor when grabbed *)
    creet.x <- float_of_int global.mouse_x -. (size /. 2.0);
    creet.y <- float_of_int global.mouse_y -. (size /. 2.0);
  ) else (
    (* Update position with velocity *)
    creet.x <- creet.x +. creet.vx;
    creet.y <- creet.y +. creet.vy;

    (* Bounce off walls *)
    if creet.x <= 0.0 || creet.x >= width_f -. size then
      creet.vx <- -.creet.vx;
    if creet.y <= 0.0 || creet.y >= height_f -. size then
      creet.vy <- -.creet.vy;
  );
  (* Clamp position *)
  creet.x <- max 0.0 (min (width_f -. size) creet.x);
  creet.y <- max 0.0 (min (height_f -. size) creet.y);

  (* Update DOM element style *)
  let creet_element = Eliom_content.Html.To_dom.of_div creet.element in
  creet_element##.style##.left := Js.string (Printf.sprintf "%.2fpx" creet.x);
  creet_element##.style##.top := Js.string (Printf.sprintf "%.2fpx" creet.y);

  (* Update grabbed class *)
  if creet.grabbed then
    creet_element##.classList##add (Js.string "grabbed")
  else
    creet_element##.classList##remove (Js.string "grabbed")

(* Simulation loop for a single creet using Lwt *)
let%client rec simulate_creet creet =
  let* () = Lwt_js.sleep 0.016 in (* ~60 FPS *)
  update_creet_position creet;
  
  (* Check if creet is in the river *)
  let (_, _, part_height) = get_stats () in
  let current_section = get_section (part_height, creet.y) in
  
  (match creet.health with
   | Healthy when current_section = "River" ->
       creet.health <- Sick { lifetime = 10.0 };
       (* Update creet element class *)
       let creet_element = Eliom_content.Html.To_dom.of_div creet.element in
       creet_element##.classList##add (Js.string "sick")
   | _ -> ()
  );
  
  simulate_creet creet

(* Check if click hit a creet *)
let%client point_in_creet creet x y =
  let size = match creet.health with
    | Mean _ -> 34.0
    | Berserk { lifetime } -> 40.0 *. lifetime
    | _ -> 40.0
  in
  let fx = float_of_int x in
  let fy = float_of_int y in
  fx >= creet.x && fx <= creet.x +. size &&
  fy >= creet.y && fy <= creet.y +. size

(* Creets container component *)
let%client creets_component () =
  let container = div ~a:[a_class ["creets-container"]] [] in
  let creets = ref [] in
  let grabbed_creet = ref None in

  (* Spawn a new creet *)
  let spawn_creet () =
    let (width, height, _) = get_stats () in
    let id = generate_unique_id () in
    let start_x = Random.float (float_of_int width -. 40.0) in
    let start_y = Random.float (float_of_int height -. 40.0) in
    let creet = create_creet id start_x start_y in

    (* Add creet to container *)
    Eliom_content.Html.Manip.appendChild container creet.element;
    creets := creet :: !creets;
    global.creet_count <- List.length !creets;

    (* Start simulation for this creet *)
    let _ = simulate_creet creet in
    ()
  in

  (* Single mousedown event listener on container *)
  let container_element = Eliom_content.Html.To_dom.of_div container in
  let _ = Dom_html.addEventListener 
    container_element
    (Dom_html.Event.mousedown)
    (Dom_html.handler (fun evt ->
      let x = evt##.clientX in
      let y = evt##.clientY in
      (* Check which creet was clicked, if any *)
      let clicked = List.find_opt (fun c -> point_in_creet c x y) !creets in
      (match clicked with
       | Some creet ->
           Dom.preventDefault evt;
           creet.grabbed <- true;
           grabbed_creet := Some creet
       | None -> ());
      Js._true))
    Js._false
  in

  (* Single global mouseup event listener *)
  let _ = Dom_html.addEventListener 
    window 
    (Dom_html.Event.mouseup)
    (Dom_html.handler (fun _ ->
      (match !grabbed_creet with
       | Some creet -> 
           creet.grabbed <- false;
           grabbed_creet := None
       | None -> ());
      Js._true))
    Js._false
  in

  (* Spawn initial creets *)
  for _i = 0 to 4 do
    spawn_creet ()
  done;

  (* Spawn new creets periodically *)
  let rec spawn_loop () =
    let* () = Lwt_js.sleep 3.0 in (* Spawn every 3 seconds *)
    spawn_creet ();
    spawn_loop ()
  in
  let _ = spawn_loop () in

  container


(* -------------- *)
(* Main COMPONENT *)
(* -------------- *)

(* Register and implement handlers and setup the index layout*)
let%shared () =
  App.register ~service:main_service (fun () () ->
    Lwt.return
      Html.F.(
        html
          (head
             (title (txt "h42n42"))
             [ css_link
                 ~uri:
                   (make_uri
                      ~service:(Eliom_service.static_dir ())
                      ["css"; "h42n42.css"])
                 () ])
          (body 
            [ Html.C.node [%client world_component ()]
            ; Html.C.node [%client 
                let hud = hud_component () in
                let creets = creets_component () in
                div [hud; creets]
              ]
            ])))